import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="fixed top-0 left-0 right-0 bg-black z-50">
        <nav className="w-full bg-black text-white font-semibold py-5 md:py-6 flex justify-between items-center px-6 md:px-12">
          <div>
            <h1 className="text-2xl md:text-3xl font-bold tracking-wide">
              Portofolio
            </h1>
          </div>
          <ul className="flex space-x-6 md:space-x-8">
            <li>
              <a
                href="#about"
                className="text-base md:text-lg hover:text-gray-300 transition-colors duration-300"
              >
                Tentang Saya
              </a>
            </li>
            <li>
              <a
                href="#message"
                className="text-base md:text-lg hover:text-gray-300 transition-colors duration-300"
              >
                Hubungi Saya
              </a>
            </li>
          </ul>
        </nav>
      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
